# Generated by Django 3.1.4 on 2021-01-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('hours', models.TextField(null=True)),
                ('calendar_ref', models.TextField(null=True)),
                ('grade_breakdown', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone', models.TextField(null=True)),
                ('office', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_type', models.TextField(null=True)),
                ('section', models.TextField(null=True)),
                ('section_type', models.TextField(null=True)),
                ('day1', models.TextField(null=True)),
                ('day2', models.TextField(null=True)),
                ('start_time', models.TextField(null=True)),
                ('end_time', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('hoursPerWeek', models.IntegerField(null=True)),
                ('studentsPerInstructor', models.TextField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('authors', models.TextField(null=True)),
                ('edition', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('is_recommended', models.TextField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('gradAttribute', models.TextField(null=True)),
                ('instLevel', models.TextField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.TextField(null=True)),
                ('learningOutcomes', models.TextField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeBreakdown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ap', models.IntegerField(null=True)),
                ('an', models.IntegerField(null=True)),
                ('am', models.IntegerField(null=True)),
                ('bp', models.IntegerField(null=True)),
                ('bn', models.IntegerField(null=True)),
                ('bm', models.IntegerField(null=True)),
                ('cp', models.IntegerField(null=True)),
                ('cn', models.IntegerField(null=True)),
                ('cm', models.IntegerField(null=True)),
                ('dp', models.IntegerField(null=True)),
                ('dn', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.instructor'),
        ),
    ]
