# Generated by Django 3.1.4 on 2021-01-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day2',
        ),
    ]
