# Generated by Django 3.1.4 on 2021-01-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20210127_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day2',
            field=models.TextField(null=True),
        ),
    ]
