# Generated by Django 3.1.4 on 2021-01-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_textbook_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='is_recommended',
            field=models.TextField(null=True),
        ),
    ]
