# Generated by Django 3.0.3 on 2020-12-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_echo'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='echoid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
