# Generated by Django 3.0.3 on 2020-12-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_echo_echoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(default=''),
        ),
    ]
