# Generated by Django 3.1.4 on 2021-01-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gradeBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('learningOutcomes', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='learningOutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='outline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('courseHours', models.IntegerField()),
                ('courseCredits', models.IntegerField()),
                ('calenderLink', models.CharField(max_length=100)),
            ],
        ),
    ]
